version: "3"

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
      POSTGRES_DB: example
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_USER: example
      DB_PASSWORD: example
      DB_HOST: db
      DB_PORT: 5434
      DB_NAME: example
      DATABASE_URL: postgresql://example:example@db/example
